### PR TITLE
Fixing errors in add and config

### PR DESCRIPTION
**Pull request by fdzedzy**
### Description

The previous fix could not add new documents or mime types because it was iterating over the current items which threw an IIS duplicate collection entry error.  

Config was also broken because it would only remove the listed documents or mime types and not remove all existing ones.  Added a second remove that covers the config scenario of removing all existing documents/mime types except for the configured ones.

Also reversed the order of add and remove so that remove executes first.  This should prevent IIS from throwing an error if trying to add items that already exist in the list when using :config.

### Issues Resolved

[[306]](https://github.com/chef-cookbooks/iis/issues/306)

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by fdzedzy** [comment]
Sorry for the multiple commits.  New to the DCO thing.

**Comment by EasyAsABC123** [comment]
Can you squash these changes? this is difficult to review in it's present form

**Comment by fdzedzy** [comment]
Do you mean the changes in processors.rb?  I think the compare looks weird because I flipped the order of add and remove.  It picks up pieces of the lines as changed.  I flipped add and remove so that we do the remove first.  That way if for example we want to clear the default document list and readd a file that already existed in the list, IIS wouldn't error when doing the add first.

**Comment by EasyAsABC123** [comment]
gotcha, but shouldn't iis notice it is already there? before trying the add?

**Comment by EasyAsABC123** [comment]
by that i mean, it shouldn't error if you have it on the add and remove list...because default_documents - documents_to_add shouldn't have any duplicates.

**Comment by fdzedzy** [comment]
No, if appcmd tries to add an entry that already exists in the IIS config, it will error with this message:  `STDOUT: ERROR ( message:New add object missing required attributes. Cannot add duplicate collection entry of type 'add' with unique key attribute 'value' set to 'Default.htm'`
This what first broke because `current_default_documents - default_documents` generated a list of documents that were already in the config.  So if someone wanted to use :config with a list of documents that included one of the original IIS entries like index.html, the full list should be removed first because if we attempt to add index.html first the add will error since it is already there.
In reality, I'm not sure how often :config would be used because if the default list of mime types is removed,  IIS basically stops functioning, but I guess it would be possible to config an exact list of mime types needed.

**Comment by EasyAsABC123** [comment]
i'm confused...if config is called and an item is already in the list that we want...we shouldn't do anything...we shouldn't delete and then re-add it.

**Comment by fdzedzy** [comment]
You are correct, since we are removing new documents from the list when we remove, we would not need to be concerned about the order of remove and add.  I believe I reordered it while testing just using the array of new documents in add.

I will swap add and remove to match the previous order.

**Comment by fdzedzy** [comment]
Yeah, it took me awhile to figure out the right combination.  The resource actions are add, delete and config and the module is called with booleans to determine if we should just add, delete or configure. These are the scenarios I came up with:

Add - (add = true, remove = false) - Add just those elements as long as they aren't already present  (default_document - current_default_documents)
Delete - (add = false, remove = true) - Remove just the elements listed (default_document - current_default_documents)
Config - (add = true, remove = true) - Add only the listed elements and delete all others present (current_default_documents - default_document)

So Add will be the same regardless of whether the action is `:add` or `:config`.  But delete will be different between `:delete` and `:config`

I feel like this logic could be more straight forward with a case or something.  The issue with the original fix was that the add had `(current_default_documents - default_document)` which threw the IIS error.  When I fixed that, I realized there were two delete scenarios because the original issue was not resolved and every other chef run caused the default documents to be deleted.

**Comment by EasyAsABC123** [comment]
thanks makes sense now thanks

**Pull request merged**
