### PR TITLE
Adds support for environment variables on app pools on IIS 10+

### PR DESCRIPTION
**Pull request by jakauppila**
### Description

Adds support for configuring environment variables on app pools on IIS 10+.

https://docs.microsoft.com/en-us/iis/configuration/system.applicationhost/applicationpools/add/environmentvariables/

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by EasyAsABC123** [comment]
Looks good to me, we probably need to get the tests running though, it looks like we need to run `chef-client --chef-license accept`  if you want to add that to the .kitchen.yml

**Comment by EasyAsABC123** [comment]
syntax failing https://github.com/chef-cookbooks/iis/pull/450/checks?check_run_id=435262580

**Comment by jakauppila** [comment]
Not sure what's going on with that latest failure.

**Comment by EasyAsABC123** [comment]
I also am unsure, it seems like an issue with the .kitchen.yml config file...
@tas50 any help here would be appreciated.

**Comment by Xorima** [comment]
why not just use the config property resource?
```
iis_config_property 'Set an environment variable' do
  ps_path   'MACHINE/WEBROOT/APPHOST'
  location  "foo.chef.io"
  filter    "system.webServer/aspNetCore/environmentVariables/environmentVariable[@name='something']"
  property  'value'
  value     'bar'
end
```

**Comment by jakauppila** [comment]
It's much more efficient to configure as I did than using `iis_config_property` for each `environment_variable`

**Pull request merged**
