### PR TITLE
Remove unused method in helper

### PR DESCRIPTION
**Pull request by kamaradclimber**
### Description

Clean unused helpers

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by EasyAsABC123** [comment]
👍  thanks

**Comment by EasyAsABC123** [comment]
this never passed CI, can you do a `git commit --amend` then just push?

**Comment by tas50** [comment]
Rebased to force CI to rebuild. No DCO is necessary since this is deletion only

**Comment by EasyAsABC123** [comment]
@tas50 thanks!

**Comment by tas50** [comment]
Merging since this passes now. Thanks @kamaradclimber

**Comment by EasyAsABC123** [comment]
Awesome

**Pull request merged**
