### PR TITLE
[GH-293] - Include all attribute in mod_management

### PR DESCRIPTION
**Pull request by roberto-mardeni**
### Description

This includes all parent dependencies for the features installed by the mod_management recipe.
This is needed to allow the user to just include mod_management recipe.

### Issues Resolved

https://github.com/chef-cookbooks/iis/issues/293

### Check List
- [x] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [x] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

* Included all attribute with value 'true' in mod_management recipe to install parent dependencies

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by roberto-mardeni** [comment]
Awesome, will update it asap

**Comment by iennae** [comment]
Thanks for the contribution @roberto-mardeni! Appreciate the thorough issue report, and the fix!

**Pull request merged**
