### PR TITLE
App Username and Password

### PR DESCRIPTION
**Pull request by CBock001**
### Description

This change allows the use of application physical path credentials in recipes. 

### Issues Resolved

no registered issues

### Check List

- [x ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ x] New functionality includes testing.
- [x ] New functionality has been documented in the README if applicable
- [ x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by EasyAsABC123** [comment]
@CBock001 sorry was in the office yesterday and didn't have a moment to look at this, will try to review right now

**Comment by EasyAsABC123** [comment]
so it appears you are just adding the ability for the vdir (or physical directory of the app) to have a username and password, have you tried it with the vdir provider? 
https://github.com/chef-cookbooks/iis/blob/master/providers/vdir.rb

**Comment by CBock001** [comment]
I just tried using vdir combined with app, it does work that way but it includes another resource in the recipe (the vdir resource) that doesn't need to be included if you can set username and password in the app itself.

**Comment by EasyAsABC123** [comment]
totally, but making this change means that both app and site providers would need to be updated to handle this.  

Also this change doesn't handle using different login methods, so support for that would need to be included.  The more I go the more this starts to be a code smell, when we have a vdir resource that does all the above, if you can get the app and site resources to use the vdir resource then we should probably go that way with it (IE have those resources call the vdir resource).

**Comment by EasyAsABC123** [comment]
@CBock001 
please take a look at this pull request and see if it does everything you need and more:
https://github.com/chef-cookbooks/iis/pull/305

**Comment by CBock001** [comment]
Yes it does, would you like me to close this PR as the one you submitted does this plus some?

**Comment by EasyAsABC123** [comment]
yes, we'll only pull the other one.  first i need to write tests and test all the use cases.

**Comment by CBock001** [comment]
Understood, I'm closing it now. Thank you

**Comment by CBock001** [comment]
Understood, I'm closing it now. Thank you

**Comment by EasyAsABC123** [comment]
not a problem, and glad i re-looked at this since it is controlling the default virtual directory (i previously didn't notice that).

**Pull request closed without merging**
