### PR TITLE
kk_add_file_extension_iis_control

### PR DESCRIPTION
**Pull request by kkennedy1**
Add the ability to control file extension inclusion and exclusions.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by EasyAsABC123** [comment]
@kkennedy1 hey! two parts
1. can you sign the CLA
2. i've gone through the code but due to merge i'm unsure exactly what the changes are

**Comment by kkennedy1** [comment]
Hello!

I've signed the ICLA.  Would you like to see any documentation from me?  All of the changes are made are named file_extensions.rb.  I've added a library, provider and resource, also a set of spec tests. Let me know if there's anything else I should do and thanks for your help.

Kevin

**Comment by EasyAsABC123** [comment]
@smurawski Can you confirm the signed ICLA? I went to the contributors page but it isn't showing up.

**Comment by kkennedy1** [comment]
Ugh, I keep getting "The Github account you are trying to link is already linked to another Supermarket user".  I must have crossed streams somewhere.  I'll get it fixed.

**Comment by smurawski** [comment]
You'll need to make sure the email address tied to the commit is also associated to the github account you've tied to your supermarket account.  The email associated to the supermarket account doesn't matter.. It's the github account, email addresses associated there, and the email on the commits.

**Comment by EasyAsABC123** [comment]
currently this shows no changes to the branch at all, closing. @kkennedy1 please re-open if needed.

**Pull request closed without merging**
