### PR TITLE
Add quotes to pool name

### PR DESCRIPTION
**Pull request by EasyAsABC123**
Signed-off-by: Justin Schuhmann <jmschu02@gmail.com>

### Description

- fixes iis_pool with spaces
- fixes tests for iis_pool with spaces

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by fdzedzy** [comment]
@EasyAsABC123 thanks for the quick help on this.

**Comment by EasyAsABC123** [comment]
@fdzedzy no worries, and this way you get the credit you deserve 👍  you found the code error, you deserve the credit.  feel free to take a look at the test commit, it contains a new test and the spec to verify it.  This is in general how i am handling and bugs found, make a new test and spec for each so that they will never return.

**Comment by fdzedzy** [comment]
Thanks! I'm new to cookbook unit testing but all the changes make sense.

**Comment by EasyAsABC123** [comment]
yup once another maintainer reviews i'll push and then release as `6.5.1`

**Pull request merged**
