### PR TITLE
Revert "set password properties as sensitive"

### PR DESCRIPTION
**Pull request by jasonwbarnett**
Reverts chef-cookbooks/iis#404

### CODE REVIEW

**Comment by jasonwbarnett** [comment]
want to revert this first?

**Comment by jasonwbarnett** [comment]
@EasyAsABC123 want to revert this first?

**Comment by EasyAsABC123** [comment]
@jasonwbarnett yes i will revert, then we will remove then you will make sensitive?

**Comment by jasonwbarnett** [comment]
@EasyAsABC123 yes. will do that.

**Pull request closed without merging**
