### PR TITLE
add option to specify dism or powershell feature install Signed-off-by: Corey Hemminger <hemminger@hotmail.com>

### PR DESCRIPTION
**Pull request by Stromweld**
Signed-off-by: Corey Hemminger <hemminger@hotmail.com>

### Description

Chef 14 defaults to powershell feature installs and this cookbook defaults to dism feature installs. Adding option to be compatible with both while maintaining current default behavior.

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by Stromweld** [comment]
appveyor failed on an unmodified file due to bad template name.

**Comment by EasyAsABC123** [comment]
@tas50 i can't merge these when they fail on appveyor, i've read the changes and they look okay.

**Comment by EasyAsABC123** [comment]
@tas50 are you able to look at this? sadly i don't have a ton of time now-a-days so i haven't been able to look at the failing tests.

**Comment by tas50** [comment]
@Stromweld Not sure where you're getting the PS default bit. Dism is still the default in Chef 14. https://github.com/chef/chef/blob/master/lib/chef/resource/windows_feature.rb#L79 sets it to dism unless you specify otherwise. This shouldn't be necessary so I'm going to close it out. Feel free to correct me here if I'm missing something, but this should all just work with Chef 14.

**Comment by Stromweld** [comment]
@tas50 been a while since we first tested this. Looking at the windows_feature in chef 14 you are correct it does default to dism install. Regardless I still think this PR is worth while to give users the option to be able to specify powershell feature names in the attribute instead of dism feature names to be installed.

**Pull request closed without merging**
